name: SonarCloud
on:
  push:
    branches:
      - master
      - Develop
      - Feature-BBDD
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Analyze with SonarCloud
      run: ./mvn -B -fn -X verify sonar:sonar -Dsonar.projectKey=Proyecto_TecnoSoftware:Proyecto_TecnoSoftware -Dsonar.organization=tecnosoftware -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
